version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: football_forecast_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-football_forecast}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - football-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: football_forecast_backend
    depends_on:
      - postgres
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-football_forecast}
      - ML_SERVICE_URL=http://ml-service:8000
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - football-network

  ml-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: football_forecast_ml
    ports:
      - "${ML_SERVICE_PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
    networks:
      - football-network

networks:
  football-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
